name: dart_backend
description: HomeConnect backend server using Dart with in-memory storage for development
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_cors_headers: ^0.1.5
  crypto: ^3.0.3
  bcrypt: ^1.1.3
  uuid: ^4.1.0
  intl: ^0.19.0
  dotenv: ^4.2.0
  # Firebase dependencies
  firebase_admin: ^0.3.0
  firebase_dart: ^1.0.5

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
